### ISSUE TITLE
Node-collector mounts for CNI binaries

### ISSUE THREAD

**Issue by dejewi** [aquasecurity/k8s-node-collector#40]
**What steps did you take and what happened:**
Node-collector cannot be deployed to GKE Dataplane V2 by Trivy because it fails to create container:

`failed to generate container "150..." spec: failed to generate spec: failed to mkdir "/opt/cni/bin/": mkdir /opt/cni: read-only file system: CreateContainerError`

**What did you expect to happen:**
node-collector runs without error

**Environment:**
- K8s-Node-Collector version: 0.0.5
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8-gke.500", GitCommit:"f117e29cb87cfb7e1de32ab4e163fb01ac5d0af9", GitTreeState:"clean", BuildDate:"2023-03-23T10:22:38Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

**Comment by chauncey-garrett** [comment]
Seeing this same problem.

**Comment by chen-keinan** [comment]
@chauncey-garrett @dejewi you can override [volumeMounts and volumes](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L544) in trivy-operator helm values

Let me know if it will solve your issue.
