### ISSUE TITLE
Support for Rancher RKE2 distribution

### ISSUE THREAD

**Issue by intonet** [aquasecurity/k8s-node-collector#89]
Hi there 
I installed the Trivi operator and encountered many cluster-level misconfiguration issues:
<img width="1655" alt="Screenshot 2024-01-19 at 11 23 34" src="https://github.com/aquasecurity/k8s-node-collector/assets/35962194/e97367dd-71b3-4102-ad46-4881a91dd156">
Rancher RKE2 is compliance with cis https://docs.rke2.io/security/cis_self_assessment123 so should pass the scans. 
The main problem I gest is scanned directories. RKE2 configurations are stored  in /etc/rancher and /var/lib/rancher/, witch are not supported in node collector.

**Comment by chen-keinan** [comment]
@intonet thanks for this input I'll have a look
